const express=require('express');const {Pool}=require('pg');const path=require('path');const app=express();app.use(express.json());app.use(express.urlencoded({extended:true}));const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:false});
const schema=`CREATE TABLE IF NOT EXISTS accounts(id SERIAL PRIMARY KEY,code VARCHAR(20) UNIQUE NOT NULL,name_ar VARCHAR(150) NOT NULL,type VARCHAR(20) NOT NULL,active BOOLEAN DEFAULT TRUE);CREATE TABLE IF NOT EXISTS patients(id SERIAL PRIMARY KEY,name VARCHAR(200) NOT NULL,phone VARCHAR(50),created_at TIMESTAMPTZ DEFAULT now());CREATE TABLE IF NOT EXISTS services(id SERIAL PRIMARY KEY,name_ar VARCHAR(150) NOT NULL,price NUMERIC(14,2) DEFAULT 0,revenue_account VARCHAR(20) DEFAULT '4101');CREATE TABLE IF NOT EXISTS journal_entries(id SERIAL PRIMARY KEY,entry_date DATE DEFAULT CURRENT_DATE,description TEXT,reference VARCHAR(100),created_at TIMESTAMPTZ DEFAULT now());CREATE TABLE IF NOT EXISTS journal_lines(id SERIAL PRIMARY KEY,entry_id INT REFERENCES journal_entries(id) ON DELETE CASCADE,account_code VARCHAR(20) NOT NULL,debit NUMERIC(14,2) DEFAULT 0,credit NUMERIC(14,2) DEFAULT 0);CREATE TABLE IF NOT EXISTS invoices(id SERIAL PRIMARY KEY,invoice_no VARCHAR(30) UNIQUE NOT NULL,patient_id INT REFERENCES patients(id),invoice_date DATE DEFAULT CURRENT_DATE,total NUMERIC(14,2) DEFAULT 0,paid NUMERIC(14,2) DEFAULT 0,status VARCHAR(20) DEFAULT 'unpaid');CREATE TABLE IF NOT EXISTS invoice_lines(id SERIAL PRIMARY KEY,invoice_id INT REFERENCES invoices(id) ON DELETE CASCADE,service_id INT REFERENCES services(id),description VARCHAR(200),qty NUMERIC(14,2) DEFAULT 1,price NUMERIC(14,2) DEFAULT 0,total NUMERIC(14,2) DEFAULT 0);CREATE TABLE IF NOT EXISTS cash_transactions(id SERIAL PRIMARY KEY,tx_date DATE DEFAULT CURRENT_DATE,type VARCHAR(30),description TEXT,amount NUMERIC(14,2) NOT NULL,reference VARCHAR(100));CREATE TABLE IF NOT EXISTS expenses(id SERIAL PRIMARY KEY,expense_date DATE DEFAULT CURRENT_DATE,description TEXT,amount NUMERIC(14,2) NOT NULL,account_code VARCHAR(20) DEFAULT '5104');CREATE TABLE IF NOT EXISTS audit_log(id SERIAL PRIMARY KEY,action VARCHAR(100),details TEXT,created_at TIMESTAMPTZ DEFAULT now());`;
const seeds=[['1101','الصندوق','asset'],['1102','البنك','asset'],['1201','ذمم المرضى','asset'],['1301','المخزون','asset'],['2101','الموردون','liability'],['2201','رواتب مستحقة','liability'],['3101','رأس المال','equity'],['4101','إيرادات العيادات','revenue'],['4102','إيرادات المختبر','revenue'],['4103','إيرادات الصيدلية','revenue'],['5101','رواتب وأجور','expense'],['5102','كهرباء ومياه','expense'],['5103','إيجار','expense'],['5104','مصروفات تشغيلية','expense']];
async function init(){await pool.query(schema);for(const s of seeds)await pool.query('INSERT INTO accounts(code,name_ar,type) VALUES($1,$2,$3) ON CONFLICT(code) DO NOTHING',s);}
app.get('/health',async(req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,system:'Wisdom Medical Accounting',database:true})}catch(e){res.status(503).json({ok:false,database:false,error:e.message})}});
app.get('/api/accounts',async(req,res)=>res.json((await pool.query('SELECT * FROM accounts ORDER BY code')).rows));
app.get('/api/patients',async(req,res)=>res.json((await pool.query('SELECT * FROM patients ORDER BY id DESC')).rows));
app.post('/api/patients',async(req,res)=>{const r=await pool.query('INSERT INTO patients(name,phone) VALUES($1,$2) RETURNING *',[req.body.name,req.body.phone||null]);await pool.query('INSERT INTO audit_log(action,details) VALUES($1,$2)',['create_patient',JSON.stringify(r.rows[0])]);res.json(r.rows[0])});
app.get('/api/services',async(req,res)=>res.json((await pool.query('SELECT * FROM services ORDER BY id')).rows));
app.post('/api/services',async(req,res)=>{const r=await pool.query('INSERT INTO services(name_ar,price,revenue_account) VALUES($1,$2,$3) RETURNING *',[req.body.name_ar,req.body.price||0,req.body.revenue_account||'4101']);res.json(r.rows[0])});
app.get('/api/dashboard',async(req,res)=>{const [i,p,e]=await Promise.all([pool.query('SELECT COALESCE(SUM(total),0) total,COALESCE(SUM(paid),0) paid FROM invoices'),pool.query('SELECT COUNT(*) count FROM patients'),pool.query('SELECT COALESCE(SUM(amount),0) total FROM expenses')]);res.json({invoices:i.rows[0],patients:Number(p.rows[0].count),expenses:e.rows[0].total})});
app.get('/api/trial-balance',async(req,res)=>{const r=await pool.query(`SELECT a.code,a.name_ar,a.type,COALESCE(SUM(l.debit),0) debit,COALESCE(SUM(l.credit),0) credit,COALESCE(SUM(l.debit-l.credit),0) balance FROM accounts a LEFT JOIN journal_lines l ON l.account_code=a.code GROUP BY a.code,a.name_ar,a.type ORDER BY a.code`);res.json(r.rows)});
app.get('/',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.use(express.static(path.join(__dirname,'public')));
const port=process.env.PORT||3000;init().then(()=>app.listen(port,()=>console.log('Wisdom Medical Accounting listening on '+port))).catch(e=>{console.error(e);process.exit(1)});